mystore/config/routes.rb
Mystore::Application.routes.draw do
  resources :search_suggestions
  get "items/all"  => "items#all"
  post "items/new" => 'items#create'
  get "items/price_by_name/:name" => "items#price_by_name"
  resources :items

  resources :bills

  post "bills/new" => 'bills#create'

   root :to => "bills#new"

end

mystore/app/models/item.rb
class Item < ActiveRecord::Base
end

mystore/app/models/search_suggestion.rb
class SearchSuggestion < ActiveRecord::Base

  def user_suggestion_params
    params.require(:SearchSuggestion).permit(:term, :popularity)
  end

  def self.terms_for(prefix)
    suggestions = where("term like ?","#{prefix}%")
    suggestions.order("popularity desc").limit(10).pluck(:term)
  end

  def self.index_products
    puts "items  are #{Item.all}"
    Item.find_each do |item|
      puts "item name is #{item.name}"
      index_term(item.name)
      item.name.split.each {|t| index_term(t)}
    end
  end

  def self.index_term(term)
    where(term: term.downcase).first_or_initialize.tap do |suggestion|
      suggestion.increment! :popularity
    end

  end
end

mystore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

mystore/app/controllers/bills_controller.rb
 class BillsController < ApplicationController
   def new
     p "bills new"
   end

   def create
     p "bills create"
     puts "posted params are #{params}"
     render 'new'
   end
   def show
     p "bills show"
     p params
   end
end

mystore/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    p "index"
  	@Items=Item.all  	
  end

  def auto
    render json: Item.term_for(params[:name])
  end

  def search
    p "search"
  end

  def show
    p "show"
    @Item=Item.find(params[:id].to_i)
  end

  def create
    p "create"
  	@Item=Item.new(:name => params["items"]["name"], :price => params["items"]["price"])
  	if @Item.save
    	redirect_to @Item
 	else
    	render 'new'
  	end  	
  end

  def edit
    p "edit"
  	@Item=Item.find(params[:id].to_i)  	
  end

  def update
    p "update"
  	@Item=Item.find(params[:id].to_i)
  	if(@Item.update_attributes(:name => params["item"]["name"], :price => params["item"]["price"].to_i))
  		redirect_to @Item
  	else
  		render 'edit'
  	end
  end

  def bill
    p "bill"
  end

  def calculate_bill
    p "calculate bill"
  end

  def all
    render json: Item.select(:name,:price,:id)
  end

  def price_by_name
    item=Item.find_by_name(params[:name])
    render json: item.price
  end


  private
  def item_params
    params.require(:item).permit(:name, :price)
  end
end

mystore/app/controllers/search_suggestions_controller.rb
class SearchSuggestionsController < ApplicationController
  def index
    p "auto suggest called with params #{params}"
     render json: SearchSuggestion.terms_for(params[:term])
  end
end

mystore/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

mystore/app/helpers/application_helper.rb
module ApplicationHelper
end

mystore/app/helpers/bills_helper.rb
module BillsHelper
end

mystore/app/helpers/items_helper.rb
module ItemsHelper
end

mystore/app/helpers/search_suggestions_helper.rb
module SearchSuggestionsHelper
end

mystore/app/helpers/welcome_helper.rb
module WelcomeHelper
end

mystore/app/views/bills/create.html.erb
<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

<script>
    function insertRow(myTable) {
        var table = document.getElementById(myTable);
        var rowCount = table.rows.length;
        var row = table.insertRow(table.rows.length);
        row.innerHTML = '<td><input type="search" class="autoc ui-autocomplete-input" name="product[]" id="product" autocomplete="off"></td>' +
                '<td><input type="text" name="price[]" id="price_" + rowCount + " value=""/>' +
                '<td><input type="text" name="quantity[]" onblur="calcItemPrice(this.id)" id="quantity_' + rowCount + '" value=""/></td>' +
                '<td><input type="text" name="item_price[]" id="item_price_" + rowCount + " value=""/>';

    }

    function calculateTotal(myTable)          {
        var table = document.getElementById(myTable);
        var tot=0;
        for(var i=1,row;row=table.rows[i];i++)
        {
            tot+=parseInt(row.cells[3].firstChild.value);
        }
        document.getElementById("total").innerHTML=tot;
    }

    function calcItemPrice(price_per_quantity){
        var itemPrice=document.getElementById(price_per_quantity).parentNode.previousElementSibling.firstChild.value * document.getElementById(price_per_quantity).value;
        document.getElementById(price_per_quantity).parentNode.nextElementSibling.firstElementChild.value=itemPrice;
    }

    function populatePrice(itemName,itemPrice_id){
        request = createRequest();
        request.open("GET","items/price_by_name/"+itemName,true);
        var response=request.send();
        alert(response);
        document.getElementById(itemPrice_id).value=response;
    }

    $( "#product" ).autocomplete({
        source: "/search_suggestions"
    });

</script>

<form name="create_bill" class="ajax" method="post" action="/bills" id="bill_form">
  <table id="myTable">
    <thead>
    <th>Item name</th>
    <th>price</th>
    <th>quantity</th>
    <th>Item price</th>
    </thead>
    <tbody>
    <tr>
      <td><input type="search" class="autoc" name="product[]" id="product"/></td>
      <td><input type="text" name ="price[]" id="price_1"/></td>
      <td><input type="text" name ="quantity[]" onblur="calcItemPrice(this.id)" id="quantity_1"/></td>
      <td><input type="text" name ="item_price[]" id="item_price_1"/></td>
    </tr>
    </tbody>
  </table>
  <label for="total">Total</label>
  <p id="total">0</p>
  <input type="button" id="btnAdd" name="addButton" class="button-add" onClick="insertRow('myTable')" value="add more items">
  <!--<input type="button" id="btnAdd" name="addButton" class="button-add" value="add more items">-->
  <input type="button" id="btnAdd" class="button-add" onClick="calculateTotal('myTable')" value="total">
  <%= submit_tag 'Submit' %>
</form>

mystore/app/views/bills/new.html.erb
<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

<script>
    function insertRow(myTable) {
        var table = document.getElementById(myTable);
        var product=table.rows[1].cells[0].lastChild.value;
        var price= table.rows[1].cells[1].lastChild.value;
        var quantity= table.rows[1].cells[2].lastChild.value;
        var item_price= table.rows[1].cells[3].lastChild.value;
//        var rowCount = table.rows.length;
//        var row = table.insertRow(table.rows.length);
//        row.innerHTML = '<td><input type="search" class="autoc ui-autocomplete-input" name="product[]" id="product" autocomplete="off"></td>' +
//                '<td><input type="text" name="price[]" id="price_" + rowCount + " value=""/>' +
//                '<td><input type="text" name="quantity[]" onblur="calcItemPrice(this.id)" id="quantity_' + rowCount + '" value=""/></td>' +
//                '<td><input type="text" name="item_price[]" id="item_price_" + rowCount + " value=""/>';
        var table1=document.getElementById("myTable1");
        var rowCount1= table1.rows.length;
        var row1=table1.insertRow(rowCount1);
        row1.innerHTML='<td><input type="text" name="product[]" id="product_'+rowCount1+'" " value='+product+'></td>'
        +'<td><input type="text" name="price[]" id="price_' + rowCount1 + '" " value='+price+'></td>'
        +'<td><input type="text" name="quantity[]" onblur="calcItemPrice(this.id)" id="quantity_'+rowCount1+'" " value='+quantity+'></td>'
        +'<td><input type="text" name="item_price[]" id="item_price_"'+rowCount1+'" " value='+item_price+'></td>';
        document.getElementById("bill_form").reset();
    }

    function calculateTotal(myTable)          {
        var table = document.getElementById(myTable);
        var tot=0;
        for(var i=0,row;row=table.rows[i];i++)
        {
           tot+=parseInt(row.cells[3].firstChild.value);
        }
        document.getElementById("total").innerHTML=tot;
    }

    function calcItemPrice(price_per_quantity){
        var itemPrice=document.getElementById(price_per_quantity).parentNode.previousElementSibling.firstChild.value * document.getElementById(price_per_quantity).value;
        document.getElementById(price_per_quantity).parentNode.nextElementSibling.firstElementChild.value=itemPrice;
    }

    function populatePrice(itemName){
      $.get("/items/price_by_name/"+itemName,function(data,status){
          document.getElementById("price").value=data
      });

    }

    function printDiv()
    {
        var divToPrint=document.getElementById('myTable1');
        newWin= window.open("");
        newWin.document.write(divToPrint.outerHTML);
        newWin.print();
        newWin.close();
    }

</script>

<form name="create_bill" class="ajax" method="post" action="/bills" id="bill_form">
    <table id="myTable">
      <thead>
      <th>Item name</th>
      <th>price</th>
      <th>quantity</th>
      <th>Item price</th>
      </thead>
      <tbody>
      <tr>
        <td><input type="search" class="autoc" name="product[]" onblur="populatePrice(this.value)" id="product"/></td>
        <td><input type="text" name ="price[]" id="price"/></td>
        <td><input type="text" name ="quantity[]" onblur="calcItemPrice(this.id)" id="quantity"/></td>
        <td><input type="text" name ="item_price[]" id="item_price"/></td>
      </tr>
      </tbody>
    </table>


    <input type="button" id="btnAdd" name="addButton" class="button-add" onClick="insertRow('myTable')" value="add more items">
  <!--<input type="button" id="btnAdd" name="addButton" class="button-add" value="add more items">-->
    <!--<input type="button" id="btnAdd" class="button-add" onClick="calculateTotal('myTable')" value="total">-->
</form>
<form name="create_bill" class="ajax" method="post" action="/bills" id="bill_form1">
<table id="myTable1">
  <tbody>
  </tbody>
</table>
  <label for="total">Total</label>
  <p id="total">0</p>
  <input type="button" id="btnAdd" class="button-add" onClick="calculateTotal('myTable1')" value="total">
  <input type="button" id="btnPrint" class="button-print" onClick="printDiv()" value="Print">
  <%= submit_tag 'Submit' %>
</form>

mystore/app/views/items/all.html.erb
<table>
  <tr>
    <td> name </td>
    <td> price </td>
  </tr>
  <% @Items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', item_path(item) %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
      </tr>
  <% end %>
</table>

mystore/app/views/items/bill.html.erb
<script>
  function some_function(){
    document.getElementById("demo").innerHTML="it worked!!"
  }

</script>
<%= form_tag('/items/calculate_bill') do   %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <p id="demo"></p>
    <%= submit_tag("Add Item", :onclick => some_function()) %>
<% end %>

mystore/app/views/items/edit.html.erb
<h1>Editing item price</h1>

<%= form_for @Item, :method => :PUT do |f| %>
	 <% if @Item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %> prohibited
        this item from being saved:
      </h2>
      <ul>
        <% @Item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
	<p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>		
  </p>
 
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

mystore/app/views/items/index.html.erb
<table>
<tr>
  <td> name </td>
  <td> price </td>
</tr>
<% @Items.each do |item| %>
<tr>
  <td><%= item.name %></td>
  <td><%= item.price %></td>
  <td><%= link_to 'Show', item_path(item) %></td>
  <td><%= link_to 'Edit', edit_item_path(item) %></td>
</tr>
<% end %>
</table>

mystore/app/views/items/new.html.erb
<%= form_for :items   do |f| %>
   <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
  <%= button_to "Add Item" %>
  </p>
<% end %>

mystore/app/views/items/search.html.erb
<p>this is search</p>

mystore/app/views/items/show.html.erb
<table>
<tr>
	<td> <%= @Item.name %></td>
	<td> <%= @Item.price %></td>	
</tr>
</table>

mystore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mystore</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

mystore/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>